### ISSUE TITLE
Fixed threshold choices

### ISSUE THREAD

**Issue by edwardnguyen1705** [ivclab/Online-Face-Recognition-and-Authentication#1]
Dear @Sherry40931 and @Jia-HongHenryLee ,
Thanks for sharing your work.
I have read your paper, and here is the points I would like to clarify that how fixed thresholds are chosen? Are these values optimal like the method described here [https://krasserm.github.io/2018/02/07/deep-face-recognition/](url)?

**Comment by Sherry40931** [comment]
Hi,

We used 10-fold cross-validation and a threshold is selected for each fold splitting, in this step, the approach of finding the threshold for each split is similar to the link you provided. The 10 thresholds selected are then averaged to yield the fixed threshold used to compare with our approach.

**Comment by edwardnguyen1705** [comment]
Just a quick follow-up question, did you observe the variation of the adaptive thresholds? I mean the time history of each adaptive threshold for each person, how far this value from its corresponding initial (fixed threshold)?

**Comment by Sherry40931** [comment]
It's an interesting idea, I didn't print out the adaptive thresholds of each person so I don't know how far they are from the initial value, which is 0, not the fixed threshold by the way. I will share my experiment result with you if I have time to do it.

**Comment by edwardnguyen1705** [comment]
Thanks for your time. Btw, if the initial threshold is 0, and assuming that the gallery has only one person, then it is likely that a new face image (of a different person) is considered as the person in the gallery. Because, it is likely that the dot product of the two embeddings is larger than 0. Maybe, I am not clear about this one.

**Comment by Sherry40931** [comment]
Yes, so if the first image is person A and the second image is person B, it will be counted as false accept. But in our experiment, after the second image was inquired, it will be inserted into the database with ground truth label. So we will get the thresholds for both the first and second images, which is the similarity of these two images. 

We believe that this flow makes sense since we often have the first image in the database in the real-world (eg. like e-gate at the airport ). So instead of using a single fixed threshold, we think using the adaptive threshold as initial is a better approach.

**Comment by edwardnguyen1705** [comment]
Thank you for your answers!
